version: '3.8'

services:
  app:
    build:
      context: ./
      args:
        - USER_ID=${USER_ID}
    env_file:
      - ./release.env
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c 'npm ci && npm start'