version: '3.8'

services:
  app:
    build:
      context: ./
      args:
        - USER_ID=${USER_ID}
    env_file:
      - ./dev.env
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    working_dir: /app
    command: bash -c 'npm ci && node index.js'