FROM node:20

ARG USER_NAME=app
ARG USER_ID=${WORKDIR}

# 引数の定義
ARG PROFILE
ARG TOKEN
ARG CLAUDE_API_KEY
ARG CLIENT_ID
ARG CHANNEL_ID_1
ARG CHANNEL_ID_2
ARG SPECIAL_CHANNEL_ID_1
ARG SPECIAL_CHANNEL_ID_2
ARG SYSTEM_PLAN
ARG SPECIAL_SYSTEM_PLAN
ARG SPECIAL_SYSTEM_PLAN_CHANNEL_ID
ARG SP_MODEL
ARG NL_MODEL
ARG VERIFY_ROLE_ID
ARG EMAIL_USER
ARG EMAIL_PASS
ARG INVITE_LINK

# 環境変数として設定
ENV PROFILE=${secrets.PROFILE}
ENV TOKEN=${secrets.TOKEN}
ENV CLAUDE_API_KEY=${secrets.CLAUDE_API_KEY}
ENV CLIENT_ID=${secrets.CLIENT_ID}
ENV CHANNEL_ID_1=${secrets.CHANNEL_ID_1}
ENV CHANNEL_ID_2=${secrets.CHANNEL_ID_2}
ENV SPECIAL_CHANNEL_ID_1=${secrets.SPECIAL_CHANNEL_ID_1}
ENV SPECIAL_CHANNEL_ID_2=${secrets.SPECIAL_CHANNEL_ID_2}
ENV SYSTEM_PLAN=${secrets.SYSTEM_PLAN}
ENV SPECIAL_SYSTEM_PLAN=${secrets.SPECIAL_SYSTEM_PLAN}
ENV SPECIAL_SYSTEM_PLAN_CHANNEL_ID=${secrets.SPECIAL_SYSTEM_PLAN_CHANNEL_ID}
ENV SP_MODEL=${secrets.SP_MODEL}
ENV NL_MODEL=${secrets.NL_MODEL}
ENV VERIFY_ROLE_ID=${secrets.VERIFY_ROLE_ID}
ENV EMAIL_USER=${secrets.EMAIL_USER}
ENV EMAIL_PASS=${secrets.EMAIL_PASS}
ENV INVITE_LINK=${secrets.INVITE_LINK}

WORKDIR /app

COPY . /app

RUN npm ci

CMD ["node", "index.js"]